### ISSUE TITLE
Chen, L., & Norman, J. 1965. Foochow-English Glossary is inaccessible from ERIC - seeking alternate download site.

### ISSUE THREAD

**Issue by jensopetersen** [ztl8702/awesome-hokchew#5]
**類型 / Type**

```
[ ] 糾錯 => 請先搜索一下之前有無別人提出過。 
[+] 新資源
```

**內容**

Chen, L., & Norman, J. 1965. Foochow-English Glossary is inaccessible from ERIC - seeking alternate download site.

**Comment by ztl8702** [comment]
Hi @jensopetersen. Sorry I could not attend to you until now. Do you mind sending me a message at my email address `ztl8702 at msn dot com` and I will see if I can find a local copy for you.

**Comment by ztl8702** [comment]
Check out my email. Closing as resolved.
